# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import federated_pb2 as proto_dot_federated__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/federated_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FederatedServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterDevice = channel.unary_unary(
                '/federated.FederatedService/RegisterDevice',
                request_serializer=proto_dot_federated__pb2.RegisterRequest.SerializeToString,
                response_deserializer=proto_dot_federated__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.UploadModelUpdate = channel.unary_unary(
                '/federated.FederatedService/UploadModelUpdate',
                request_serializer=proto_dot_federated__pb2.ModelUpdateRequest.SerializeToString,
                response_deserializer=proto_dot_federated__pb2.ModelUpdateResponse.FromString,
                _registered_method=True)
        self.DownloadGlobalModel = channel.unary_unary(
                '/federated.FederatedService/DownloadGlobalModel',
                request_serializer=proto_dot_federated__pb2.GlobalModelRequest.SerializeToString,
                response_deserializer=proto_dot_federated__pb2.GlobalModelResponse.FromString,
                _registered_method=True)
        self.ReportMetrics = channel.unary_unary(
                '/federated.FederatedService/ReportMetrics',
                request_serializer=proto_dot_federated__pb2.MetricsRequest.SerializeToString,
                response_deserializer=proto_dot_federated__pb2.MetricsResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/federated.FederatedService/Heartbeat',
                request_serializer=proto_dot_federated__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=proto_dot_federated__pb2.HeartbeatResponse.FromString,
                _registered_method=True)


class FederatedServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterDevice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadModelUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadGlobalModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FederatedServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterDevice,
                    request_deserializer=proto_dot_federated__pb2.RegisterRequest.FromString,
                    response_serializer=proto_dot_federated__pb2.RegisterResponse.SerializeToString,
            ),
            'UploadModelUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadModelUpdate,
                    request_deserializer=proto_dot_federated__pb2.ModelUpdateRequest.FromString,
                    response_serializer=proto_dot_federated__pb2.ModelUpdateResponse.SerializeToString,
            ),
            'DownloadGlobalModel': grpc.unary_unary_rpc_method_handler(
                    servicer.DownloadGlobalModel,
                    request_deserializer=proto_dot_federated__pb2.GlobalModelRequest.FromString,
                    response_serializer=proto_dot_federated__pb2.GlobalModelResponse.SerializeToString,
            ),
            'ReportMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportMetrics,
                    request_deserializer=proto_dot_federated__pb2.MetricsRequest.FromString,
                    response_serializer=proto_dot_federated__pb2.MetricsResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=proto_dot_federated__pb2.HeartbeatRequest.FromString,
                    response_serializer=proto_dot_federated__pb2.HeartbeatResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'federated.FederatedService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('federated.FederatedService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FederatedService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/federated.FederatedService/RegisterDevice',
            proto_dot_federated__pb2.RegisterRequest.SerializeToString,
            proto_dot_federated__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadModelUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/federated.FederatedService/UploadModelUpdate',
            proto_dot_federated__pb2.ModelUpdateRequest.SerializeToString,
            proto_dot_federated__pb2.ModelUpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadGlobalModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/federated.FederatedService/DownloadGlobalModel',
            proto_dot_federated__pb2.GlobalModelRequest.SerializeToString,
            proto_dot_federated__pb2.GlobalModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/federated.FederatedService/ReportMetrics',
            proto_dot_federated__pb2.MetricsRequest.SerializeToString,
            proto_dot_federated__pb2.MetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/federated.FederatedService/Heartbeat',
            proto_dot_federated__pb2.HeartbeatRequest.SerializeToString,
            proto_dot_federated__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
