package cmd

import (
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

var completionCmd = &cobra.Command{
	Use:   "completion [bash|zsh|powershell]",
	Short: "生成命令行自动补全脚本",
	Long: `为bash、zsh或powershell生成自动补全脚本。

安装方法:

Bash:
  # 临时生效
  source <(dbdoctor completion bash)

  # 永久生效 (Linux)
  dbdoctor completion bash > /etc/bash_completion.d/dbdoctor

  # 永久生效 (macOS)
  dbdoctor completion bash > /usr/local/etc/bash_completion.d/dbdoctor

Zsh:
  # 如果启用了补全系统
  source <(dbdoctor completion zsh)

  # 永久生效
  dbdoctor completion zsh > "${fpath[1]}/_dbdoctor"

  # 或者添加到 ~/.zshrc:
  echo 'source <(dbdoctor completion zsh)' >> ~/.zshrc

PowerShell:
  dbdoctor completion powershell | Out-String | Invoke-Expression

  # 永久生效
  dbdoctor completion powershell > $profile
`,
	ValidArgs: []string{"bash", "zsh", "powershell"},
	Args:      cobra.ExactValidArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		switch args[0] {
		case "bash":
			return rootCmd.GenBashCompletion(os.Stdout)
		case "zsh":
			return genZshCompletion()
		case "powershell":
			return rootCmd.GenPowerShellCompletion(os.Stdout)
		default:
			return fmt.Errorf("unsupported shell type: %s", args[0])
		}
	},
}

func genZshCompletion() error {
	zshHead := fmt.Sprintf(`#compdef _dbdoctor dbdoctor

# dbdoctor zsh completion script
# Generated by dbdoctor completion zsh
# To install, save this file to a directory in your $fpath:
#   dbdoctor completion zsh > "${fpath[1]}/_dbdoctor"

function _dbdoctor {
  local -a commands

  _arguments -C \
    '1: :->cmds' \
    '*:: :->args'

  case $state in
    cmds)
      commands=(
        "init:初始化配置文件"
        "node:节点管理命令"
        "rebalance:手动触发lease和replica重分配"
        "backup:集群备份与恢复管理"
        "completion:生成命令行自动补全脚本"
        "help:显示帮助信息"
      )
      _describe -t commands 'dbdoctor commands' commands
      ;;
    args)
      case $words[1] in
        node)
          _dbdoctor_node
          ;;
        rebalance)
          _dbdoctor_rebalance
          ;;
        backup)
          _dbdoctor_backup
          ;;
        completion)
          _dbdoctor_completion
          ;;
        *)
          _files
          ;;
      esac
      ;;
  esac
}

function _dbdoctor_node {
  local -a subcommands
  subcommands=(
    "status:显示集群节点状态"
  )
  _describe -t commands 'node commands' subcommands

  _arguments \
    '(-c --cluster)'{-c,--cluster}'[cluster name to operate on]:cluster:->clusters' \
    '(-d --details)'{-d,--details}'[show detailed node information]' \
    '(-H --health)'{-H,--health}'[include heartbeat health check]' \
    '--json[output in JSON format]'
}

function _dbdoctor_rebalance {
  _arguments \
    '(-c --cluster)'{-c,--cluster}'[cluster name to operate on]:cluster:->clusters' \
    '--leases-only[only rebalance leases]' \
    '--replicas-only[only rebalance replicas]' \
    '(-w --wait)'{-w,--wait}'[wait for operation to complete]' \
    '--timeout[timeout in seconds for wait]:timeout: ' \
    '--json[output in JSON format]'

  local -a subcommands
  subcommands=(
    "sql:使用SQL函数触发重分配"
  )
  _describe -t commands 'rebalance commands' subcommands
}

function _dbdoctor_backup {
  _arguments \
    '(-c --cluster)'{-c,--cluster}'[cluster name to operate on]:cluster:->clusters' \
    '--full[create full backup]' \
    '--incremental[create incremental backup]' \
    '--incremental-from[base backup path for incremental]:path:_files' \
    '(-e --encryption)'{-e,--encryption}'[encryption passphrase]:passphrase: ' \
    '--target-time[target time for point-in-time restore]:time: ' \
    '(-d --database)'{-d,--database}'[target database name for restore]:database: ' \
    '(-l --list)'{-l,--list}'[list available backups]' \
    '(-r --restore)'{-r,--restore}'[restore from backup]' \
    '--job-id[check backup/restore job status]:job_id: ' \
    '--prefix[S3 key prefix for backups]:prefix: ' \
    '--json[output in JSON format]'
}

function _dbdoctor_completion {
  local -a shells
  shells=(
    "bash:生成bash自动补全脚本"
    "zsh:生成zsh自动补全脚本"
    "powershell:生成powershell自动补全脚本"
  )
  _describe -t shells 'shell types' shells
}

_dbdoctor "$@"
`)

	fmt.Print(zshHead)
	return nil
}

func init() {
	rootCmd.AddCommand(completionCmd)
}
