import { v4 as uuidv4 } from 'uuid';
import * as fs from 'fs';
import * as path from 'path';
import {
  Document,
  Paragraph,
  Table,
  TableCell,
  TableRow,
  ImageRun,
  HeadingLevel,
  Packer,
  AlignmentType,
  WidthType,
  BorderStyle,
  TextRun,
  PageBreak,
  ShadingType,
} from 'docx';
import type {
  AnomalyResult,
  SHAPResult,
  TimeSeriesData,
  HMMConfig,
  ReportConfig,
  ReportResult,
} from '../../shared/types.js';
import { dataStore } from './datastore.js';
import { mean, stdDev } from './utils.js';

const i18n = {
  zh: {
    title: '异常根因分析报告',
    subtitle: '基于HMM模型的时间序列异常检测',
    date: '报告日期',
    timeRange: '时间范围',
    summary: '摘要统计',
    anomalyOverview: '异常概览',
    totalDataPoints: '总数据点数',
    anomalyCount: '异常数量',
    anomalyRatio: '异常占比',
    maxScore: '最大异常得分',
    avgScore: '平均异常得分',
    timelineChart: '时序图 - 异常高亮',
    logLikelihoodChart: '对数似然曲线',
    shapBarChart: 'SHAP特征重要性排名',
    shapWaterfallChart: 'SHAP瀑布图 - 典型异常点',
    rootCauseAnalysis: '根因分析',
    drivingFeatures: '驱动特征贡献度',
    featureName: '特征名称',
    meanAbsShap: '平均|SHAP|值',
    contribution: '贡献度',
    modelParams: '检测模型参数',
    hmmConfig: 'HMM配置',
    nStates: '状态数量',
    learningRate: '学习率',
    anomalyThreshold: '异常阈值倍数',
    maxIterations: '最大迭代次数',
    convergenceTolerance: '收敛容差',
    appendices: '附录',
    rawAnomalies: '原始异常点列表',
    timestamp: '时间戳',
    logLikelihood: '对数似然值',
    anomalyScore: '异常得分',
    state: '隐藏状态',
    page: '第',
    pageOf: '页',
    generatedBy: '本报告由异常检测系统自动生成',
  },
  en: {
    title: 'Anomaly Root Cause Analysis Report',
    subtitle: 'HMM-based Time Series Anomaly Detection',
    date: 'Report Date',
    timeRange: 'Time Range',
    summary: 'Summary Statistics',
    anomalyOverview: 'Anomaly Overview',
    totalDataPoints: 'Total Data Points',
    anomalyCount: 'Anomaly Count',
    anomalyRatio: 'Anomaly Ratio',
    maxScore: 'Max Anomaly Score',
    avgScore: 'Avg Anomaly Score',
    timelineChart: 'Timeline Chart - Anomaly Highlight',
    logLikelihoodChart: 'Log Likelihood Curve',
    shapBarChart: 'SHAP Feature Importance Ranking',
    shapWaterfallChart: 'SHAP Waterfall Plot - Typical Anomaly',
    rootCauseAnalysis: 'Root Cause Analysis',
    drivingFeatures: 'Driving Feature Contributions',
    featureName: 'Feature Name',
    meanAbsShap: 'Mean |SHAP| Value',
    contribution: 'Contribution %',
    modelParams: 'Detection Model Parameters',
    hmmConfig: 'HMM Configuration',
    nStates: 'Number of States',
    learningRate: 'Learning Rate',
    anomalyThreshold: 'Anomaly Threshold (K)',
    maxIterations: 'Max Iterations',
    convergenceTolerance: 'Convergence Tolerance',
    appendices: 'Appendices',
    rawAnomalies: 'Raw Anomaly Points List',
    timestamp: 'Timestamp',
    logLikelihood: 'Log Likelihood',
    anomalyScore: 'Anomaly Score',
    state: 'Hidden State',
    page: 'Page',
    pageOf: 'of',
    generatedBy: 'This report is auto-generated by Anomaly Detection System',
  },
};

function formatNumber(n: number, decimals: number = 2): string {
  if (!isFinite(n)) return 'N/A';
  const factor = Math.pow(10, decimals);
  return (Math.round(n * factor) / factor).toFixed(decimals);
}

function formatDate(date: Date | string): string {
  const d = typeof date === 'string' ? new Date(date) : date;
  const year = d.getFullYear();
  const month = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');
  const hours = String(d.getHours()).padStart(2, '0');
  const minutes = String(d.getMinutes()).padStart(2, '0');
  return `${year}-${month}-${day} ${hours}:${minutes}`;
}

function getTopAnomalies(
  result: AnomalyResult,
  topN: number = 10
): Array<{ timestamp: string; logLikelihood: number; anomalyScore: number; state: number; index: number }> {
  const anomalies: Array<{ timestamp: string; logLikelihood: number; anomalyScore: number; state: number; index: number }> = [];
  
  for (let i = 0; i < result.timestamps.length; i++) {
    if (result.anomalies[i]) {
      anomalies.push({
        timestamp: result.timestamps[i],
        logLikelihood: result.logLikelihoods[i],
        anomalyScore: result.anomalyScores[i],
        state: result.states[i],
        index: i,
      });
    }
  }
  
  anomalies.sort((a, b) => b.anomalyScore - a.anomalyScore);
  return anomalies.slice(0, topN);
}

function summarizeSHAP(shapResult: SHAPResult): {
  featureName: string;
  meanAbsShap: number;
  contributionPercent: number;
  rank: number;
}[] {
  const totalMeanAbsShap = Object.values(shapResult.meanAbsShap).reduce((sum, val) => sum + Math.abs(val), 0);
  
  const features = shapResult.featureNames.map((name, index) => ({
    featureName: name,
    meanAbsShap: shapResult.meanAbsShap[name],
    contributionPercent: totalMeanAbsShap > 0 ? (Math.abs(shapResult.meanAbsShap[name]) / totalMeanAbsShap) * 100 : 0,
    rank: index + 1,
  }));
  
  return features.sort((a, b) => b.meanAbsShap - a.meanAbsShap);
}

async function generateAnomalyChart(
  timestamps: string[],
  values: number[],
  anomalies: boolean[]
): Promise<string> {
  const anomalyIndices: number[] = [];
  const anomalyValues: number[] = [];
  const anomalyRanges: Array<{ start: number; end: number }> = [];
  
  for (let i = 0; i < anomalies.length; i++) {
    if (anomalies[i]) {
      anomalyIndices.push(i);
      anomalyValues.push(values[i]);
    }
  }
  
  let rangeStart = -1;
  for (let i = 0; i < anomalies.length; i++) {
    if (anomalies[i] && rangeStart === -1) {
      rangeStart = i;
    } else if (!anomalies[i] && rangeStart !== -1) {
      anomalyRanges.push({ start: rangeStart, end: i - 1 });
      rangeStart = -1;
    }
  }
  if (rangeStart !== -1) {
    anomalyRanges.push({ start: rangeStart, end: anomalies.length - 1 });
  }
  
  const svgContent = generateSimpleLineChart(
    timestamps.map((_, i) => i),
    values,
    anomalyRanges,
    'Time Series with Anomalies'
  );
  
  return `data:image/svg+xml;base64,${Buffer.from(svgContent).toString('base64')}`;
}

async function generateLogLikelihoodChart(
  timestamps: string[],
  logLikelihoods: number[],
  threshold: number
): Promise<string> {
  const thresholdLine = new Array(timestamps.length).fill(threshold);
  
  const svgContent = generateSimpleLineChartWithThreshold(
    timestamps.map((_, i) => i),
    logLikelihoods,
    threshold,
    'Log Likelihood Curve'
  );
  
  return `data:image/svg+xml;base64,${Buffer.from(svgContent).toString('base64')}`;
}

async function generateSHAPBarChart(
  featureNames: string[],
  meanAbsShap: Record<string, number>
): Promise<string> {
  const features = [...featureNames].sort((a, b) => meanAbsShap[b] - meanAbsShap[a]).slice(0, 15);
  const values = features.map(f => Math.abs(meanAbsShap[f]));
  
  const svgContent = generateSimpleBarChart(
    features,
    values,
    'SHAP Feature Importance'
  );
  
  return `data:image/svg+xml;base64,${Buffer.from(svgContent).toString('base64')}`;
}

async function generateSHAPWaterfallChart(
  shapResult: SHAPResult,
  anomalyIndex: number = 0
): Promise<string> {
  const features = shapResult.featureNames.slice(0, 10);
  const shapValues = features.map(f => {
    const vals = shapResult.shapValues[f];
    return vals.length > anomalyIndex ? vals[anomalyIndex] : (vals[0] || 0);
  });
  
  const svgContent = generateWaterfallChart(
    features,
    shapValues,
    shapResult.baseValue,
    'SHAP Waterfall Plot'
  );
  
  return `data:image/svg+xml;base64,${Buffer.from(svgContent).toString('base64')}`;
}

function generateSimpleLineChart(
  xValues: number[],
  yValues: number[],
  highlightRanges: Array<{ start: number; end: number }>,
  title: string
): string {
  const width = 800;
  const height = 400;
  const padding = 60;
  
  const xMin = Math.min(...xValues);
  const xMax = Math.max(...xValues);
  const yMin = Math.min(...yValues) * 0.99;
  const yMax = Math.max(...yValues) * 1.01;
  
  const xScale = (x: number) => padding + ((x - xMin) / (xMax - xMin)) * (width - 2 * padding);
  const yScale = (y: number) => height - padding - ((y - yMin) / (yMax - yMin)) * (height - 2 * padding);
  
  let pathData = '';
  for (let i = 0; i < xValues.length; i++) {
    const x = xScale(xValues[i]);
    const y = yScale(yValues[i]);
    pathData += i === 0 ? `M ${x} ${y}` : ` L ${x} ${y}`;
  }
  
  let highlightRects = '';
  for (const range of highlightRanges) {
    const x1 = xScale(range.start);
    const x2 = xScale(range.end);
    highlightRects += `<rect x="${x1}" y="${padding}" width="${Math.max(x2 - x1, 2)}" height="${height - 2 * padding}" fill="rgba(255, 100, 100, 0.3)" />`;
  }
  
  return `
    <svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}">
      <rect x="0" y="0" width="${width}" height="${height}" fill="white"/>
      <text x="${width / 2}" y="25" text-anchor="middle" font-family="Arial" font-size="16" font-weight="bold">${title}</text>
      <line x1="${padding}" y1="${height - padding}" x2="${width - padding}" y2="${height - padding}" stroke="#333" stroke-width="1"/>
      <line x1="${padding}" y1="${padding}" x2="${padding}" y2="${height - padding}" stroke="#333" stroke-width="1"/>
      ${highlightRects}
      <path d="${pathData}" fill="none" stroke="#3498db" stroke-width="2"/>
      <text x="${width / 2}" y="${height - 10}" text-anchor="middle" font-family="Arial" font-size="12">Time Index</text>
      <text x="15" y="${height / 2}" text-anchor="middle" font-family="Arial" font-size="12" transform="rotate(-90, 15, ${height / 2})">Value</text>
    </svg>
  `.trim();
}

function generateSimpleLineChartWithThreshold(
  xValues: number[],
  yValues: number[],
  threshold: number,
  title: string
): string {
  const width = 800;
  const height = 400;
  const padding = 60;
  
  const xMin = Math.min(...xValues);
  const xMax = Math.max(...xValues);
  const yMin = Math.min(Math.min(...yValues), threshold) * 0.99;
  const yMax = Math.max(Math.max(...yValues), threshold) * 1.01;
  
  const xScale = (x: number) => padding + ((x - xMin) / (xMax - xMin)) * (width - 2 * padding);
  const yScale = (y: number) => height - padding - ((y - yMin) / (yMax - yMin)) * (height - 2 * padding);
  
  let pathData = '';
  for (let i = 0; i < xValues.length; i++) {
    const x = xScale(xValues[i]);
    const y = yScale(yValues[i]);
    pathData += i === 0 ? `M ${x} ${y}` : ` L ${x} ${y}`;
  }
  
  const thresholdY = yScale(threshold);
  const thresholdLine = `<line x1="${padding}" y1="${thresholdY}" x2="${width - padding}" y2="${thresholdY}" stroke="#e74c3c" stroke-width="2" stroke-dasharray="5,5"/>`;
  
  return `
    <svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}">
      <rect x="0" y="0" width="${width}" height="${height}" fill="white"/>
      <text x="${width / 2}" y="25" text-anchor="middle" font-family="Arial" font-size="16" font-weight="bold">${title}</text>
      <line x1="${padding}" y1="${height - padding}" x2="${width - padding}" y2="${height - padding}" stroke="#333" stroke-width="1"/>
      <line x1="${padding}" y1="${padding}" x2="${padding}" y2="${height - padding}" stroke="#333" stroke-width="1"/>
      <path d="${pathData}" fill="none" stroke="#2ecc71" stroke-width="2"/>
      ${thresholdLine}
      <text x="${width - padding - 5}" y="${thresholdY - 5}" text-anchor="end" font-family="Arial" font-size="11" fill="#e74c3c">Threshold: ${formatNumber(threshold, 2)}</text>
      <text x="${width / 2}" y="${height - 10}" text-anchor="middle" font-family="Arial" font-size="12">Time Index</text>
      <text x="15" y="${height / 2}" text-anchor="middle" font-family="Arial" font-size="12" transform="rotate(-90, 15, ${height / 2})">Log Likelihood</text>
    </svg>
  `.trim();
}

function generateSimpleBarChart(
  labels: string[],
  values: number[],
  title: string
): string {
  const width = 800;
  const height = Math.max(400, labels.length * 35 + 100);
  const padding = { left: 180, right: 40, top: 60, bottom: 40 };
  
  const maxValue = Math.max(...values) * 1.1;
  const barHeight = 25;
  const barSpacing = 35;
  
  const xScale = (v: number) => padding.left + (v / maxValue) * (width - padding.left - padding.right);
  
  let bars = '';
  let labelsText = '';
  let valueLabels = '';
  
  for (let i = 0; i < labels.length; i++) {
    const y = padding.top + i * barSpacing;
    const barWidth = xScale(values[i]) - padding.left;
    const color = `hsl(${(i * 30) % 360}, 70%, 50%)`;
    
    bars += `<rect x="${padding.left}" y="${y}" width="${Math.max(barWidth, 2)}" height="${barHeight}" fill="${color}" rx="3"/>`;
    labelsText += `<text x="${padding.left - 10}" y="${y + barHeight / 2 + 4}" text-anchor="end" font-family="Arial" font-size="11">${labels[i].length > 20 ? labels[i].slice(0, 17) + '...' : labels[i]}</text>`;
    valueLabels += `<text x="${padding.left + barWidth + 5}" y="${y + barHeight / 2 + 4}" text-anchor="start" font-family="Arial" font-size="11">${formatNumber(values[i], 4)}</text>`;
  }
  
  return `
    <svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}">
      <rect x="0" y="0" width="${width}" height="${height}" fill="white"/>
      <text x="${width / 2}" y="30" text-anchor="middle" font-family="Arial" font-size="16" font-weight="bold">${title}</text>
      ${bars}
      ${labelsText}
      ${valueLabels}
    </svg>
  `.trim();
}

function generateWaterfallChart(
  features: string[],
  values: number[],
  baseValue: number,
  title: string
): string {
  const width = 800;
  const height = Math.max(400, features.length * 35 + 120);
  const padding = { left: 150, right: 40, top: 70, bottom: 50 };
  
  const allValues = [baseValue, ...values];
  let current = baseValue;
  const cumulative: number[] = [baseValue];
  for (const v of values) {
    current += v;
    cumulative.push(current);
  }
  
  const minVal = Math.min(...cumulative) * 1.1;
  const maxVal = Math.max(...cumulative) * 1.1;
  const valueRange = maxVal - minVal || 1;
  
  const barWidth = 25;
  const barSpacing = 35;
  
  const yScale = (v: number) => height - padding.bottom - ((v - minVal) / valueRange) * (height - padding.top - padding.bottom);
  
  let bars = '';
  let labelsText = '';
  let connectors = '';
  
  const baseY = yScale(baseValue);
  bars += `<rect x="${padding.left - 40}" y="${Math.min(baseY, yScale(0))}" width="${barWidth + 10}" height="${Math.abs(baseY - yScale(0))}" fill="#95a5a6" rx="2"/>`;
  labelsText += `<text x="${padding.left - 25}" y="${height - padding.bottom + 20}" text-anchor="middle" font-family="Arial" font-size="10" font-weight="bold">Base</text>`;
  labelsText += `<text x="${padding.left - 25}" y="${baseY - 5}" text-anchor="middle" font-family="Arial" font-size="9" fill="#666">${formatNumber(baseValue, 2)}</text>`;
  
  let prevY = baseY;
  let prevX = padding.left - 15;
  
  for (let i = 0; i < features.length; i++) {
    const x = padding.left + i * barSpacing + 20;
    const startY = yScale(cumulative[i]);
    const endY = yScale(cumulative[i + 1]);
    const color = values[i] >= 0 ? '#e74c3c' : '#3498db';
    
    bars += `<rect x="${x}" y="${Math.min(startY, endY)}" width="${barWidth}" height="${Math.max(Math.abs(startY - endY), 1)}" fill="${color}" rx="2"/>`;
    labelsText += `<text x="${x + barWidth / 2}" y="${height - padding.bottom + 20}" text-anchor="middle" font-family="Arial" font-size="9">${features[i].length > 10 ? features[i].slice(0, 7) + '...' : features[i]}</text>`;
    connectors += `<line x1="${prevX}" y1="${prevY}" x2="${x}" y2="${startY}" stroke="#95a5a6" stroke-width="1" stroke-dasharray="3,3"/>`;
    
    prevX = x + barWidth;
    prevY = endY;
  }
  
  return `
    <svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}">
      <rect x="0" y="0" width="${width}" height="${height}" fill="white"/>
      <text x="${width / 2}" y="30" text-anchor="middle" font-family="Arial" font-size="16" font-weight="bold">${title}</text>
      <line x1="${padding.left - 40}" y1="${yScale(0)}" x2="${width - padding.right}" y2="${yScale(0)}" stroke="#ccc" stroke-width="1"/>
      ${connectors}
      ${bars}
      ${labelsText}
      <text x="${width / 2}" y="${height - 10}" text-anchor="middle" font-family="Arial" font-size="12">Features</text>
    </svg>
  `.trim();
}

function createHeading(text: string, level: (typeof HeadingLevel)[keyof typeof HeadingLevel]): Paragraph {
  return new Paragraph({
    text,
    heading: level,
    spacing: { before: 200, after: 200 },
  });
}

function createParagraph(text: string, options: { bold?: boolean; size?: number } = {}): Paragraph {
  return new Paragraph({
    children: [
      new TextRun({
        text,
        bold: options.bold || false,
        size: options.size ? options.size * 2 : 24,
      }),
    ],
    spacing: { after: 100 },
  });
}

function createTable(
  headers: string[],
  rows: string[][]
): Table {
  const tableRows: TableRow[] = [];
  
  tableRows.push(
    new TableRow({
      children: headers.map(
        (h) =>
          new TableCell({
            children: [new Paragraph({ text: h, alignment: AlignmentType.CENTER })],
            shading: { type: ShadingType.SOLID, fill: 'E8E8E8' },
            width: { size: 100 / headers.length, type: WidthType.PERCENTAGE },
          })
      ),
    })
  );
  
  for (const row of rows) {
    tableRows.push(
      new TableRow({
        children: row.map(
          (cell) =>
            new TableCell({
              children: [new Paragraph({ text: cell, alignment: AlignmentType.CENTER })],
            })
        ),
      })
    );
  }
  
  return new Table({
    rows: tableRows,
    width: { size: 100, type: WidthType.PERCENTAGE },
    borders: {
      top: { style: BorderStyle.SINGLE, size: 1 },
      bottom: { style: BorderStyle.SINGLE, size: 1 },
      left: { style: BorderStyle.SINGLE, size: 1 },
      right: { style: BorderStyle.SINGLE, size: 1 },
      insideHorizontal: { style: BorderStyle.SINGLE, size: 1 },
      insideVertical: { style: BorderStyle.SINGLE, size: 1 },
    },
  });
}

async function createImageParagraph(imageData: string, width: number = 600, height: number = 300): Promise<Paragraph> {
  const base64Data = imageData.split(',')[1];
  const imageBuffer = Buffer.from(base64Data, 'base64');
  
  return new Paragraph({
    children: [
      new ImageRun({
        data: imageBuffer,
        transformation: { width, height },
        type: 'svg',
      } as unknown as any),
    ],
    alignment: AlignmentType.CENTER,
    spacing: { before: 200, after: 200 },
  });
}

export async function generateReport(
  anomalyResult: AnomalyResult,
  data: TimeSeriesData,
  shapResult: SHAPResult | null,
  config: ReportConfig & { hmmConfig: HMMConfig }
): Promise<Buffer> {
  const lang = config.language || 'zh';
  const t = i18n[lang];
  
  const anomalyCount = anomalyResult.anomalies.filter(Boolean).length;
  const anomalyRatio = anomalyCount / anomalyResult.anomalies.length;
  const maxScore = Math.max(...anomalyResult.anomalyScores);
  const avgScore = mean(anomalyResult.anomalyScores.filter(s => s > 0));
  
  const priceFeature = data.selectedFeatures[0] || Object.keys(data.features)[0];
  const priceValues = data.features[priceFeature] || [];
  
  const children = [];
  
  children.push(
    new Paragraph({
      text: t.title,
      heading: HeadingLevel.TITLE,
      alignment: AlignmentType.CENTER,
      spacing: { before: 2000, after: 200 },
    })
  );
  
  children.push(
    new Paragraph({
      text: t.subtitle,
      alignment: AlignmentType.CENTER,
      spacing: { after: 1000 },
    })
  );
  
  children.push(createParagraph(`${t.date}: ${formatDate(new Date())}`));
  children.push(
    createParagraph(
      `${t.timeRange}: ${anomalyResult.timestamps[0]} - ${anomalyResult.timestamps[anomalyResult.timestamps.length - 1]}`
    )
  );
  children.push(new PageBreak());
  
  children.push(createHeading(t.anomalyOverview, HeadingLevel.HEADING_1));
  
  const overviewRows = [
    [t.totalDataPoints, String(anomalyResult.timestamps.length)],
    [t.anomalyCount, String(anomalyCount)],
    [t.anomalyRatio, `${formatNumber(anomalyRatio * 100, 2)}%`],
    [t.maxScore, formatNumber(maxScore, 4)],
    [t.avgScore, formatNumber(avgScore, 4)],
  ];
  children.push(createTable(['Metric', 'Value'], overviewRows));
  
  if (config.includeCharts) {
    children.push(createHeading(t.timelineChart, HeadingLevel.HEADING_1));
    const anomalyChart = await generateAnomalyChart(
      anomalyResult.timestamps,
      priceValues,
      anomalyResult.anomalies
    );
    children.push(await createImageParagraph(anomalyChart, 600, 300));
    
    children.push(createHeading(t.logLikelihoodChart, HeadingLevel.HEADING_1));
    const llChart = await generateLogLikelihoodChart(
      anomalyResult.timestamps,
      anomalyResult.logLikelihoods,
      anomalyResult.threshold
    );
    children.push(await createImageParagraph(llChart, 600, 300));
  }
  
  if (config.includeSHAP && shapResult) {
    children.push(createHeading(t.shapBarChart, HeadingLevel.HEADING_1));
    const shapBarChart = await generateSHAPBarChart(
      shapResult.featureNames,
      shapResult.meanAbsShap
    );
    children.push(await createImageParagraph(shapBarChart, 600, Math.max(300, shapResult.featureNames.length * 30)));
    
    children.push(createHeading(t.shapWaterfallChart, HeadingLevel.HEADING_1));
    const shapWaterfallChart = await generateSHAPWaterfallChart(shapResult, 0);
    children.push(await createImageParagraph(shapWaterfallChart, 600, 350));
    
    children.push(createHeading(t.rootCauseAnalysis, HeadingLevel.HEADING_1));
    children.push(createParagraph(t.drivingFeatures, { bold: true }));
    
    const shapSummary = summarizeSHAP(shapResult).slice(0, 10);
    const shapRows = shapSummary.map((s) => [
      String(s.rank),
      s.featureName,
      formatNumber(s.meanAbsShap, 6),
      `${formatNumber(s.contributionPercent, 2)}%`,
    ]);
    children.push(
      createTable(['Rank', t.featureName, t.meanAbsShap, t.contribution], shapRows)
    );
  }
  
  children.push(createHeading(t.modelParams, HeadingLevel.HEADING_1));
  children.push(createParagraph(t.hmmConfig, { bold: true }));
  
  const configRows = [
    [t.nStates, String(config.hmmConfig.nStates)],
    [t.learningRate, String(config.hmmConfig.learningRate)],
    [t.anomalyThreshold, String(config.hmmConfig.anomalyThreshold)],
    [t.maxIterations, String(config.hmmConfig.maxIterations)],
    [t.convergenceTolerance, String(config.hmmConfig.convergenceTolerance)],
  ];
  children.push(createTable(['Parameter', 'Value'], configRows));
  
  if (config.includeRawData) {
    children.push(new PageBreak());
    children.push(createHeading(t.appendices, HeadingLevel.HEADING_1));
    children.push(createHeading(t.rawAnomalies, HeadingLevel.HEADING_2));
    
    const topAnomalies = getTopAnomalies(anomalyResult, 50);
    const anomalyRows = topAnomalies.map((a) => [
      a.timestamp,
      formatNumber(a.logLikelihood, 4),
      formatNumber(a.anomalyScore, 4),
      String(a.state),
    ]);
    
    if (anomalyRows.length > 0) {
      children.push(
        createTable(
          [t.timestamp, t.logLikelihood, t.anomalyScore, t.state],
          anomalyRows
        )
      );
    }
  }
  
  children.push(new Paragraph({
    text: t.generatedBy,
    alignment: AlignmentType.CENTER,
    spacing: { before: 500 },
    children: [
      new TextRun({
        text: t.generatedBy,
        italics: true,
        color: '888888',
        size: 20,
      }),
    ],
  }));
  
  const doc = new Document({
    sections: [
      {
        properties: {},
        children,
      },
    ],
  });
  
  return Packer.toBuffer(doc);
}

export async function saveReport(
  buffer: Buffer,
  filename: string
): Promise<ReportResult> {
  const reportsDir = path.join(process.cwd(), 'public', 'reports');
  
  if (!fs.existsSync(reportsDir)) {
    fs.mkdirSync(reportsDir, { recursive: true });
  }
  
  const fullPath = path.join(reportsDir, filename);
  fs.writeFileSync(fullPath, buffer);
  
  const stats = fs.statSync(fullPath);
  
  return {
    id: uuidv4(),
    fileName: filename,
    fileSize: stats.size,
    createdAt: new Date().toISOString(),
    downloadUrl: `/reports/${filename}`,
  };
}

export async function generateAndSaveReport(
  anomalyResult: AnomalyResult,
  data: TimeSeriesData,
  shapResult: SHAPResult | null,
  config: ReportConfig & { hmmConfig: HMMConfig }
): Promise<ReportResult> {
  const buffer = await generateReport(anomalyResult, data, shapResult, config);
  const filename = `anomaly-report-${Date.now()}.docx`;
  return saveReport(buffer, filename);
}

export {
  formatNumber,
  formatDate,
  getTopAnomalies,
  summarizeSHAP,
  generateAnomalyChart,
  generateLogLikelihoodChart,
  generateSHAPBarChart,
  generateSHAPWaterfallChart,
};

export default {
  generateReport,
  saveReport,
  generateAndSaveReport,
};
